version: '2'
services:
 mongodb:
   image: mongo:3.3   
   expose:                 
     - "27017"
   volumes:
     - db_data:/data/db
   environment:    
    MONGODB_DATABASE: rsvpdata
   networks:
    - rsvpnet

 web:
   image: venky626/rsvpapp:mooc
   ports:
    - "5000:5000"
   environment:
    MONGODB_HOST: mongodb
    LINK: http://www.meetup.com/cloudyuga/
    TEXT1: Venky 
    TEXT2: Garage RSVP!
    LOGO: https://raw.githubusercontent.com/venky626/rsvpapp/master/static/cloudyuga.png
    COMPANY: Venky Technology Pvt. Ltd.
   networks:
    - rsvpnet

networks:
  rsvpnet:

volumes:
   db_data:
